name: Deploy
# Trigger deployment only on push to master branch
on:
    push:
        branches:
            - main

permissions:
    id-token: write   # This is required for requesting the JWT
    contents: read    # This is required for actions/checkout

jobs:
    deploy:
        name: Deploy on server push on main branch
        runs-on: ubuntu-latest

        steps:
            - name: Git clone checkout repository
              uses: actions/checkout@v3

            - name: Install Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '18.13'

            - name: Deploy
              uses: easingthemes/ssh-deploy@main
              with:
                  SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
                  REMOTE_HOST: ${{ secrets.HOST_DNS }}
                  REMOTE_USER: ${{ secrets.USERNAME }}
                  TARGET: ${{ secrets.TARGET }}

            - name: Build and Run
              env:
                  SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
                  HOST_DNS: ${{ secrets.HOST_DNS }}
                  USERNAME: ${{ secrets.USERNAME }}
                  NODE_PORT: ${{ secrets.NODE_PORT }}
              run: |
                    cd
                    ssh -o StrictHostKeyChecking=no -i $HOME/private_key ${USERNAME}@${HOST_DNS} '
                    source /home/ubuntu/.profile &&
                    cd tipsandtricks &&
                    export NVM_DIR=/home/ubuntu/.nvm &&
                    source /home/ubuntu/.nvm/nvm.sh &&
                    npm install && npm run build &&
                    npm run restart
                    '
