name: Node.js CI

on: [push]

#
jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [18.x]
        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
            - name: 'Create env file'
              run: |
                  touch .env
                  echo ROUND_SALT_PWD=10 >> .env
                  echo JWT_SECRET_ACCESS='secret_access' >> .env
                  echo JWT_SECRET_REFRESH='secret_refresh' >> .env
                  echo JWT_ACCESS_EXPIRATION='5m' >> .env
                  echo JWT_REFRESH_EXPIRATION='1d' >> .env
                  cat .env
            - run: npm ci
            - run: npm run build --if-present
            - run: npm run test
            - run: npm run pretty-lint
