name: Push-to-EC2

# Trigger deployment only on push to master branch
on:
    push:
        branches:
            - main

jobs:
    deploy:
        name: Deploy to EC2 on push on main branch
        runs-on: ubuntu-latest

        steps:
            - name: Checkout the files
              uses: actions/checkout@v2

            - name: Deploy to EC2
              uses: easingthemes/ssh-deploy@main
              env:
                  SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
                  HOST_DNS: ${{ secrets.HOST_DNS }}
                  USERNAME: ${{ secrets.USERNAME }}

              run:
                  echo "$SSH_PRIVATE_KEY" > private_key && chmod 600 private_key
                  ssh -o StrictHostKeyChecking=no -i private_key ${USERNAME}@${HOST_DNS} '
                
                # Now we have got the access of EC2 and we will start the deploy .
                  cd /home/ec2-user/projet-07-tips-and-tricks-back/ &&
                  git checkout main &&
                  git fetch --all &&
                  git pull origin main &&
                  sudo npm i &&
                  sudo npm run build &&
                  sudo pm2 stop ./dist/index.js &&
                  sudo pm2 start ./dist/index.js
                  '
